spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  output:
    ansi:
      enabled: ALWAYS
  
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
    dateformat: dd-MM-yyyy HH:mm:ss
  include-application-name: false
