build:
  version: "3.0 (Local/Default Profile) from Config Server (Resources Classpath)"

accounts:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1345
